name: iOS

on: [pull_request]

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: yarn install --immutable --immutable-cache --check-cache

      - run: pod install
        working-directory: ios
        name: Install pod dependencies

      - name: Build iOS (debug)
        run: "xcodebuild \
          -workspace ios/syenah_app.xcodeproj \
          -scheme syenah_app \
          clean archive \
          -sdk iphoneos \
          -configuration Debug \
          -UseModernBuildSystem=NO \
          -archivePath $PWD/syenah_app \
          CODE_SIGNING_ALLOWED=NO"
